package me.rerere.rikkahub.data.model

import kotlinx.serialization.Serializable
import me.rerere.rikkahub.data.db.entity.MemNodeType
import me.rerere.rikkahub.data.db.entity.MemReality
import me.rerere.rikkahub.data.db.entity.MemScope
import me.rerere.rikkahub.data.db.entity.MemSensitivity

/**
 * Domain layer for the graph memory store: the closed op vocabulary (§5.2) that models may propose,
 * plus the type-specific `extra` payload. The [me.rerere.rikkahub.data.memory.MemoryOpApplier] is
 * the only code that turns these into node/edge writes, under its guardrails and dedup gate.
 */

/**
 * Decoded `memory_node.extra` payload. Everything is optional; unknown keys are ignored on decode
 * (JsonInstant `ignoreUnknownKeys = true`) so the shape can grow without a migration.
 */
@Serializable
data class MemoryExtra(
    /** ENTITY: alternative surface forms ("uni", "die Uni" for "TU Wien"). Learned per user. */
    val aliases: List<String> = emptyList(),
    /** FACT: coarse category consumed by the scope-promotion whitelist (name/pronouns/…). */
    val category: String? = null,
    /** GOAL lifecycle state (OPEN/PRIMED/ASKED/…), question text and value note. */
    val goalState: String? = null,
    val goalQuestion: String? = null,
    val valueNote: String? = null,
    /** GOAL: draft answer from an optional web lookup, stored unconfirmed. */
    val goalDraftAnswer: String? = null,
    /** HABIT: human-readable cadence descriptor ("usually studies late at night"). */
    val habitCadence: String? = null,
    /** FRAME: descriptor of the mode ("roleplay mode", "study-buddy chat"). */
    val frameLabel: String? = null,
    /** FACT: proposed validity horizon in millis from recorded_at, if the model suggested one. */
    val validityHorizonMillis: Long? = null,
)

/** Goal lifecycle states, stored in [MemoryExtra.goalState]. */
object MemoryGoalState {
    const val OPEN = "OPEN"
    const val PRIMED = "PRIMED"
    const val ASKED = "ASKED"
    const val CONFIRMED = "CONFIRMED"
    const val DECLINED = "DECLINED"
    const val IGNORED = "IGNORED"
    const val COOLDOWN = "COOLDOWN"
    const val ABANDONED = "ABANDONED"
}

/** Coarse user-fact categories tagged at extraction; the closed promotion whitelist is a subset. */
object MemoryFactCategory {
    const val NAME = "name"
    const val PRONOUNS = "pronouns"
    const val LANGUAGE = "language"
    const val TIMEZONE = "timezone"
    const val OCCUPATION_STUDY = "occupation_study"
    const val OTHER = "other"

    /** Categories that may auto-promote CHARACTER→GLOBAL_USER without a confirmation chip (§6.5). */
    val PROMOTION_WHITELIST = setOf(NAME, PRONOUNS, LANGUAGE, TIMEZONE, OCCUPATION_STUDY)
}

/**
 * The closed set of operations a model (or importer/tool) may propose. Deterministic sleep-pass-only
 * ops (MERGE/COMPRESS/PROMOTE_SCOPE/DECAY) are NOT here — they are generated by code, never proposed.
 *
 * Note there is intentionally no DELETE and no in-place UPDATE: an [UpdateNode] creates a new node
 * plus a SUPERSEDES edge, and forgetting is a scheduled, reversible-until-grace process.
 */
sealed interface MemoryOp {
    /** Per-op provenance: excerpt of the source text and the model's one-line rationale. */
    val rationale: String
    val excerpt: String

    data class AddNode(
        val type: Int, // MemNodeType
        val content: String,
        /** Entity labels this node is ABOUT; resolved/created into hubs by the applier. */
        val entities: List<String> = emptyList(),
        val scope: Int? = null, // null → applier decides (CHARACTER by default)
        val aliases: List<String> = emptyList(),
        val category: String? = null,
        val importance: Int = 3,
        val confidence: Float = 0.7f,
        val sensitivity: Int = MemSensitivity.NORMAL,
        val reality: Int = MemReality.REAL,
        val frame: String? = null,
        val eventStart: Long? = null,
        val eventEnd: Long? = null,
        val validFrom: Long? = null,
        val validUntil: Long? = null,
        val validityHorizonMillis: Long? = null,
        override val rationale: String = "",
        override val excerpt: String = "",
    ) : MemoryOp

    /** RELATES_TO / CONTRADICTS between two existing node ids known from the neighborhood digest. */
    data class AddEdge(
        val fromId: String,
        val toId: String,
        val type: Int, // MemEdgeType
        override val rationale: String = "",
        override val excerpt: String = "",
    ) : MemoryOp

    data class Reinforce(
        val id: String,
        val note: String? = null,
        override val rationale: String = "",
        override val excerpt: String = "",
    ) : MemoryOp

    data class UpdateNode(
        val oldId: String,
        val content: String,
        val importance: Int? = null,
        val confidence: Float? = null,
        val validUntil: Long? = null,
        override val rationale: String = "",
        override val excerpt: String = "",
    ) : MemoryOp

    data class CloseNode(
        val id: String,
        val endedAt: Long? = null,
        override val rationale: String = "",
        override val excerpt: String = "",
    ) : MemoryOp

    data class OpenGoal(
        val question: String,
        val entities: List<String> = emptyList(),
        val valueNote: String = "",
        override val rationale: String = "",
        override val excerpt: String = "",
    ) : MemoryOp

    data class ResolveGoal(
        val id: String,
        val outcome: String, // MemoryGoalState.CONFIRMED / DECLINED / …
        val learned: String? = null,
        override val rationale: String = "",
        override val excerpt: String = "",
    ) : MemoryOp
}

/** Result of an applier run — used for the activity summary and unit tests. */
data class MemoryApplyResult(
    val added: List<String> = emptyList(),      // node ids created
    val reinforced: List<String> = emptyList(), // node ids reinforced
    val updated: List<String> = emptyList(),    // node ids superseded by a new version
    val closed: List<String> = emptyList(),
    val goalsOpened: List<String> = emptyList(),
    val goalsResolved: List<String> = emptyList(),
    val flaggedForAdjudication: List<String> = emptyList(),
    val dropped: Int = 0, // ops rejected by guardrails
) {
    val changed: Boolean
        get() = added.isNotEmpty() || reinforced.isNotEmpty() || updated.isNotEmpty() ||
            closed.isNotEmpty() || goalsOpened.isNotEmpty() || goalsResolved.isNotEmpty()

    val touchedNodeIds: List<String>
        get() = (added + reinforced + updated + closed + goalsOpened + goalsResolved).distinct()
}

/** Maps between the model-facing node-type strings and the persisted int codes. */
object MemoryNodeTypeCodec {
    fun fromString(s: String?): Int? = when (s?.trim()?.uppercase()) {
        "ENTITY" -> MemNodeType.ENTITY
        "FACT" -> MemNodeType.FACT
        "EPISODE" -> MemNodeType.EPISODE
        "HABIT" -> MemNodeType.HABIT
        "FRAME" -> MemNodeType.FRAME
        "GOAL" -> MemNodeType.GOAL
        "GIST" -> MemNodeType.GIST
        else -> null
    }

    fun toString(code: Int): String = when (code) {
        MemNodeType.ENTITY -> "ENTITY"
        MemNodeType.FACT -> "FACT"
        MemNodeType.EPISODE -> "EPISODE"
        MemNodeType.HABIT -> "HABIT"
        MemNodeType.FRAME -> "FRAME"
        MemNodeType.GOAL -> "GOAL"
        MemNodeType.GIST -> "GIST"
        else -> "FACT"
    }
}

/** Maps the model-facing scope strings to int codes. */
object MemoryScopeCodec {
    fun fromString(s: String?): Int? = when (s?.trim()?.uppercase()) {
        "GLOBAL", "GLOBAL_USER", "USER", "SHARED", "SHARED_USER" -> MemScope.GLOBAL_USER
        "CHARACTER", "PRIVATE" -> MemScope.CHARACTER
        else -> null
    }
}
